"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {Loader2,LockKeyhole,CheckCircle2,AlertCircle} from "lucide-react";
import {createClient} from "../../../lib/supabase/client";
import styles from "../../../components/auth.module.css";
export default function ResetPassword(){
 const [password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[ready,setReady]=useState(false),[checking,setChecking]=useState(true),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{createClient().auth.getSession().then(({data})=>{if(data.session)setReady(true);else setError("This reset link is invalid or has expired. Please request a new one.");setChecking(false)})},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(loading)return;setError("");setMessage("");if(password.length<8)return setError("Password must be at least 8 characters.");if(password!==confirm)return setError("Passwords do not match.");setLoading(true);try{const {error}=await createClient().auth.updateUser({password});if(error)setError(error.message);else setMessage("Your password has been updated. You can now sign in.");}catch(err){setError(err instanceof Error?err.message:"We couldn't update your password. Please try again.");}finally{setLoading(false)}}
 return <main className={styles.page}><div className={styles.shell}><section className={styles.formSide}><div className={styles.formHeader}><span className={styles.kicker}>SECURE RECOVERY</span><h1 className={styles.heading}>Set a new password</h1><p className={styles.sub}>Choose a new password for your Myshop account.</p></div>{checking?<div className={styles.loadingState}><Loader2 size={22} className={styles.spin}/><span>Verifying your secure link...</span></div>:ready?<form onSubmit={submit} className={styles.form}><label className={styles.label}>New password<input className={styles.input} required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className={styles.label}>Confirm password<input className={styles.input} required minLength={8} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{error&&<div className={styles.error}><AlertCircle size={16}/><span>{error}</span></div>}{message&&<div className={styles.success}><CheckCircle2 size={17}/><span>{message} <Link href="/login">Sign in</Link></span></div>}<button disabled={loading} className={styles.submit}>{loading?<><Loader2 size={17} className={styles.spin}/>Updating password...</>:<><LockKeyhole size={17}/>Update password</>}</button></form>:<div className={styles.error}><AlertCircle size={16}/><span>{error}</span></div>}</section></div></main>;
}