"use client";
import Link from "next/link";
import {useState} from "react";
import {ShieldCheck,ShoppingBag,Truck,Loader2,AlertCircle} from "lucide-react";
import {createClient} from "../../../lib/supabase/client";
import styles from "../../../components/auth.module.css";

export default function Login(){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[googleLoading,setGoogleLoading]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();if(loading||googleLoading)return;setError("");setLoading(true);try{const{error}=await createClient().auth.signInWithPassword({email:email.trim(),password});if(error)setError(error.message);else location.href="/";}catch(err){setError(err instanceof Error?err.message:"We couldn't sign you in. Please try again.");}finally{setLoading(false)}}
 async function google(){if(loading||googleLoading)return;setError("");setGoogleLoading(true);try{const{error}=await createClient().auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin+"/auth/callback?next=/"}});if(error){setError(error.message);setGoogleLoading(false)}}catch(err){setError(err instanceof Error?err.message:"Google sign-in failed.");setGoogleLoading(false)}}
 return <main className={styles.page}><div className={styles.shell}><section className={styles.visual}><div className={styles.brand}>MY<span className={styles.accent}>SHOP</span></div><h2>Everything you need, in one place.</h2><p>Discover products, follow your orders and shop securely from any device.</p><div className={styles.benefits}><div className={styles.benefit}><ShoppingBag size={15}/> Easy shopping and order management</div><div className={styles.benefit}><ShieldCheck size={15}/> Secure account and checkout</div><div className={styles.benefit}><Truck size={15}/> Order tracking from your account</div></div></section><section className={styles.formSide}><div className={styles.formHeader}><span className={styles.kicker}>WELCOME BACK</span><h1 className={styles.heading}>Welcome back</h1><p className={styles.sub}>Sign in to continue shopping.</p></div><form onSubmit={submit} className={styles.form}><label className={styles.label}>Email<input className={styles.input} type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label className={styles.label}>Password<input className={styles.input} type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/></label>{error&&<div className={styles.error}><AlertCircle size={16}/><span>{error}</span></div>}<button disabled={loading||googleLoading} className={styles.submit}>{loading?<><Loader2 size={17} className={styles.spin}/>Signing in...</>:<>Sign in</>}</button><button type="button" disabled={loading||googleLoading} onClick={google} className={styles.google}>{googleLoading?<><Loader2 size={17} className={styles.spin}/>Connecting...</>:<>Continue with Google</>}</button><p className={styles.foot}><Link href="/forgot-password">Forgot password?</Link></p><p className={styles.foot}>New to Myshop? <Link href="/register">Create an account</Link></p></form></section></div></main>
}