"use client";
import Link from "next/link";
import {useState} from "react";
import {Loader2,MailCheck,AlertCircle,ArrowLeft} from "lucide-react";
import {createClient} from "../../../lib/supabase/client";
import styles from "../../../components/auth.module.css";
export default function ForgotPassword(){
 const[email,setEmail]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();if(loading)return;setMessage("");setError("");setLoading(true);try{const {error}=await createClient().auth.resetPasswordForEmail(email.trim(),{redirectTo:window.location.origin+"/auth/callback?next=/reset-password"});if(error)setError(error.message);else setMessage("If an account exists for that email, a password reset link has been sent.");}catch(err){setError(err instanceof Error?err.message:"We couldn't send the reset email. Please try again.");}finally{setLoading(false)}}
 return <main className={styles.page}><div className={styles.shell}><section className={styles.formSide}><Link href="/login" className={styles.back}><ArrowLeft size={15}/> Back to sign in</Link><div className={styles.formHeader}><span className={styles.kicker}>ACCOUNT RECOVERY</span><h1 className={styles.heading}>Forgot password?</h1><p className={styles.sub}>Enter your email and we'll send you a secure password reset link.</p></div><form onSubmit={submit} className={styles.form}><label className={styles.label}>Email<input className={styles.input} required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>{error&&<div className={styles.error}><AlertCircle size={16}/><span>{error}</span></div>}{message&&<div className={styles.success}><MailCheck size={17}/><span>{message}</span></div>}<button disabled={loading} className={styles.submit}>{loading?<><Loader2 size={17} className={styles.spin}/>Sending secure link...</>:<>Send reset link</>}</button></form></section></div></main>;
}