import LegalPage from "../../../../components/LegalPage";
export default function Privacy(){return <LegalPage title="Privacy Policy" intro="This policy explains what personal information Myshop collects, why we use it, how we protect it, and the choices available to customers, sellers and visitors." updated="19 September 2026" sections={[
{title:"1. Information we collect",body:<><p>We may collect account information such as name, email address, phone number, profile photo, username and delivery information. We collect order information including products purchased, quantities, prices, payment references, delivery details and order status. We also collect technical information such as browser/device information, session information, security events and product interaction data such as searches, product views, wishlist activity and cart activity.</p></>},
{title:"2. How we use information",body:<p>We use information to create and secure accounts, process payments, fulfill orders, calculate stock, provide delivery and tracking updates, maintain carts and wishlists, personalize product discovery, prevent fraud and abuse, provide customer support, troubleshoot the service, improve reliability and comply with legal obligations.</p>},
{title:"3. Payments",body:<p>Payment details are processed through our payment provider. Myshop does not intentionally store full card numbers or payment authentication secrets. We receive payment status, transaction references and related verification information needed to reconcile an order.</p>},
{title:"4. Product recommendations and activity",body:<p>Myshop may use recent product views, searches, category or brand interactions, ratings and popularity signals to organize product recommendations. This information is used to improve discovery and is not sold as a personal profile.</p>},
{title:"5. Sharing information",body:<p>We share information only when necessary to operate the service, such as with payment, hosting, storage, authentication and delivery-related service providers, or when required by law. We do not sell customer personal information as a product.</p>},
{title:"6. Retention and deletion",body:<p>We retain information for as long as reasonably necessary for account operation, order records, security, dispute resolution, accounting and legal requirements. You may request account deletion or other privacy assistance through support. Some records may need to be retained where legally required.</p>},
{title:"7. Security",body:<p>We use authentication controls, database access policies, encrypted connections and server-side handling of sensitive payment credentials. No internet service can guarantee absolute security, so customers should protect passwords, verification codes and devices.</p>},
{title:"8. Your choices",body:<p>You can review and update profile information, manage saved items, sign out, request account deactivation or deletion, and contact support about privacy concerns. Browser cookie controls can also be used where applicable.</p>},
{title:"9. Children",body:<p>Myshop is intended for people who can legally enter into purchases and accounts. We do not knowingly design the service to collect personal information from children.</p>},
{title:"10. Changes",body:<p>We may update this policy as the service changes. The latest version will be published on this page with its updated date.</p>}
]}/>}