"use client";
import {useEffect,useRef,useState} from "react";
import {createClient} from "../../../lib/supabase/client";
import {PackageOpen,UserRound,MapPin,Settings,ShoppingBag,LogOut,Trash2,Camera,Shield,Info,Save} from "lucide-react";
import styles from "./account.module.css";

export default function Account(){
 const [user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>({}),[orders,setOrders]=useState<any[]>([]),[tab,setTab]=useState("profile"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[notifications,setNotifications]=useState(true);
 const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){location.href="/login";return}setUser(user);const[{data:p,error:pe},{data:o}]=await Promise.all([s.from("profiles").select("*").eq("id",user.id).single(),s.from("orders").select("*").eq("user_id",user.id).order("created_at",{ascending:false})]);if(pe){setMsg(pe.message);return}setProfile(p||{})})()},[]);
 const email=user?.email||profile.email||""; const fallback=(profile.full_name||email||"User").trim().slice(0,1).toUpperCase(); const generated="https://api.dicebear.com/9.x/initials/svg?seed="+encodeURIComponent(email||"myshop-user")+"&backgroundColor=f97316&fontWeight=800";
 const avatar=profile.avatar_url||user?.user_metadata?.avatar_url||user?.user_metadata?.picture||generated;
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg("");const s=createClient();const{error}=await s.from("profiles").update({full_name:profile.full_name||null,phone:profile.phone||null,username:profile.username||null,location:profile.location||null,about:profile.about||null,website:profile.website||null}).eq("id",user.id);setMsg(error?error.message:"Profile updated successfully.");setBusy(false)}
 async function upload(file:File){if(!file.type.startsWith("image/")||file.size>5*1024*1024){setMsg("Choose an image under 5MB.");return}setUploading(true);setMsg("");const s=createClient();const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=user.id+"/avatar."+ext;const{error}=await s.storage.from("avatars").upload(path,file,{upsert:true,contentType:file.type});if(error){setMsg(error.message);setUploading(false);return}const{data}=s.storage.from("avatars").getPublicUrl(path);const{error:pe}=await s.from("profiles").update({avatar_url:data.publicUrl}).eq("id",user.id);setMsg(pe?pe.message:"Profile photo updated.");if(!pe)setProfile({...profile,avatar_url:data.publicUrl});setUploading(false)}
 async function logout(){const s=createClient();await s.auth.signOut();location.href="/"}
 async function deactivate(){if(!confirm("Deactivate your account? You will be signed out and can contact support to reactivate it."))return;setBusy(true);const s=createClient();const{error}=await s.from("profiles").update({is_deactivated:true}).eq("id",user.id);if(error)setMsg(error.message);else{await s.auth.signOut();location.href="/"}setBusy(false)}
 async function deleteAccount(){if(!confirm("Delete your Myshop account permanently? This cannot be undone."))return;setBusy(true);const r=await fetch("/api/account/delete",{method:"DELETE"});const data=await r.json();if(!r.ok){setMsg(data.error||"Unable to delete account.");setBusy(false);return}const s=createClient();await s.auth.signOut();location.href="/"}
 const nav=[["profile","Profile",UserRound],["orders","Orders",ShoppingBag],["location","Location",MapPin],["settings","Settings",Settings],["security","Security",Shield],["about","About",Info]];
 return <section className={styles.shell}>
  <aside className={styles.side}>{nav.map(([key,label,Icon]:any)=><button key={key} className={styles.sideButton+" "+(tab===key?styles.active:"")} onClick={()=>setTab(key)}><Icon size={18}/>{label}</button>)}<button className={styles.sideButton} onClick={logout}><LogOut size={18}/>Log out</button></aside>
  <main className={styles.content}>
   <div className={styles.hero}><div>{avatar?<img src={avatar} className={styles.avatar} alt="Profile"/>:<div className={styles.initials}>{fallback}</div>}</div><div className={styles.heroText}><h1>{profile.full_name||"Your profile"}</h1><p>{email}</p>{profile.username&&<p>@{profile.username}</p>}</div><label className={styles.upload}><Camera size={18}/> {uploading?"Uploading...":"Change photo"}<input ref={fileRef} type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div>
   {tab==="profile"&&<form className={styles.panel} onSubmit={save}><h2>Profile information</h2><p className={styles.muted}>Control the information other parts of Myshop can use for your account.</p><div className={styles.grid}><div className={styles.field}><label>Full name</label><input className={styles.input} value={profile.full_name||""} onChange={e=>setProfile({...profile,full_name:e.target.value})}/></div><div className={styles.field}><label>Username</label><input className={styles.input} value={profile.username||""} onChange={e=>setProfile({...profile,username:e.target.value})} placeholder="yourname"/></div><div className={styles.field}><label>Email</label><input className={styles.input} value={email} disabled/></div><div className={styles.field}><label>Phone</label><input className={styles.input} value={profile.phone||""} onChange={e=>setProfile({...profile,phone:e.target.value})}/></div><div className={styles.field+" "+styles.full}><label>About</label><textarea className={styles.textarea} value={profile.about||""} onChange={e=>setProfile({...profile,about:e.target.value})} placeholder="Tell people a little about yourself"/></div><div className={styles.field}><label>Website</label><input className={styles.input} value={profile.website||""} onChange={e=>setProfile({...profile,website:e.target.value})} placeholder="https://"/></div></div><div className={styles.actions}><button className={styles.primary} disabled={busy}><Save size={16}/>{busy?"Saving...":"Save changes"}</button></div>{msg&&<p className={styles.message}>{msg}</p>}</form>}
   {tab==="location"&&<form className={styles.panel} onSubmit={save}><h2>Location</h2><p className={styles.muted}>Keep your delivery and marketplace location information up to date.</p><div className={styles.field} style={{marginTop:20}}><label>Location</label><input className={styles.input} value={profile.location||""} onChange={e=>setProfile({...profile,location:e.target.value})} placeholder="City, region or delivery area"/></div><div className={styles.actions}><button className={styles.primary} disabled={busy}><MapPin size={16}/>Save location</button></div></form>}
   {tab==="orders"&&<div className={styles.panel}><h2>Your orders</h2>{orders.length?<div className={styles.orders}>{orders.map(o=><div className={styles.order} key={o.id}><div><b>{o.order_number}</b><p className={styles.muted}>GHS {Number(o.total).toFixed(2)}</p></div><span>{o.status}</span></div>)}</div>:<div className={styles.empty}><PackageOpen size={30}/><p>No orders yet.</p></div>}</div>}
   {tab==="settings"&&<div className={styles.panel}><h2>Settings</h2><div className={styles.settingRow}><div><div className={styles.settingTitle}>Email notifications</div><div className={styles.settingDescription}>Receive account and order updates by email.</div></div><button type="button" className={styles.switch+" "+(notifications?styles.switchOn:"")} onClick={()=>setNotifications(!notifications)}><div className={styles.knob}/></button></div><div className={styles.settingRow}><div><div className={styles.settingTitle}>Profile visibility</div><div className={styles.settingDescription}>Your basic profile can be used across Myshop services.</div></div><span>Private by default</span></div></div>}
   {tab==="security"&&<div className={styles.panel}><h2>Security & account access</h2><p className={styles.muted}>Manage how you access Myshop.</p><div className={styles.actions}><button className={styles.secondary} onClick={()=>location.href="/forgot-password"}>Change password</button><button className={styles.secondary} onClick={logout}><LogOut size={16}/>Log out</button></div><div className={styles.panel+" "+styles.dangerPanel} style={{marginTop:24}}><h2>Danger zone</h2><div className={styles.actions}><button className={styles.dangerButton} onClick={deactivate} disabled={busy}>Deactivate account</button><button className={styles.dangerButton} onClick={deleteAccount} disabled={busy}><Trash2 size={16}/>Delete account</button></div></div></div>}
   {tab==="about"&&<div className={styles.panel}><h2>About your Myshop account</h2><p className={styles.muted}>Your account profile is used for shopping, orders, saved preferences and future marketplace features.</p><div className={styles.settingRow}><span>Account email</span><strong>{email}</strong></div><div className={styles.settingRow}><span>Member since</span><strong>{profile.created_at?new Date(profile.created_at).toLocaleDateString():"—"}</strong></div></div>}
  </main>
 </section>
}