import LegalPage from "../../../components/LegalPage";
export default function Terms(){return <LegalPage title="Terms of Service" intro="These terms explain the rules for using Myshop, creating an account, purchasing products, communicating with support and using marketplace features." updated="19 September 2026" sections={[
{title:"1. Accepting the terms",body:<p>By accessing Myshop or creating an account, you agree to use the service lawfully and responsibly. If you do not agree, do not use the service.</p>},
{title:"2. Accounts",body:<p>You are responsible for providing accurate information, keeping your credentials secure and notifying us if you believe your account has been compromised. One person must not impersonate another person or create accounts for fraudulent purposes.</p>},
{title:"3. Products and pricing",body:<p>Product descriptions, images, prices, stock levels and availability may change. We aim to display accurate information, but an error may occur. If an order cannot reasonably be fulfilled, we may contact you and arrange an appropriate cancellation or refund according to the applicable payment and return rules.</p>},
{title:"4. Orders",body:<p>An order is recorded after payment is successfully verified and the order creation process completes. Customers should review products, quantities, delivery details and totals before payment. Order status and tracking information may change as fulfillment progresses.</p>},
{title:"5. Payments",body:<p>Payments are processed through the payment provider shown at checkout. Myshop verifies successful transactions before creating paid orders. Customers must not attempt charge manipulation, payment fraud, duplicate fulfillment or unauthorized payment reversals.</p>},
{title:"6. Returns and refunds",body:<p>Return eligibility depends on the product, condition, delivery status and applicable seller or platform rules. Customers should inspect delivered products promptly and contact support with the order number and evidence when a product is damaged, incorrect or materially different from its listing.</p>},
{title:"7. Prohibited use",body:<p>Do not use Myshop for fraud, harassment, unauthorized access, malware, scraping that harms the service, payment abuse, impersonation, unlawful goods, misleading listings or attempts to bypass security controls.</p>},
{title:"8. Service availability",body:<p>We work to keep Myshop available but cannot guarantee uninterrupted access. Maintenance, provider outages, network failures and security events may temporarily affect features.</p>},
{title:"9. Liability",body:<p>To the extent permitted by applicable law, Myshop is not responsible for losses caused by misuse of an account, inaccurate information supplied by a customer, third-party outages, or events outside reasonable control.</p>},
{title:"10. Changes and termination",body:<p>We may update features or suspend accounts involved in serious abuse, fraud or security threats. Updated terms will be published here.</p>}
]}/>}